vich_uploader:
    db_driver: orm

    mappings:
       annonce_images:
           uri_prefix: '%annonce_images%'
           upload_destination: '%kernel.project_dir%/public%annonce_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           delete_on_update: true
           delete_on_remove: true

